package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppointmentserviceId generated by hbm2java
 */
@Embeddable
public class AppointmentServiceId implements java.io.Serializable {

	private int serviceId;
	private int appointmentId;

	public AppointmentServiceId() {
	}

	public AppointmentServiceId(int serviceId, int appointmentId) {
		this.serviceId = serviceId;
		this.appointmentId = appointmentId;
	}

	@Column(name = "service_id", nullable = false)
	public int getserviceId() {
		return this.serviceId;
	}

	public void setserviceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "appointment_id", nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppointmentServiceId))
			return false;
		AppointmentServiceId castOther = (AppointmentServiceId) other;

		return (this.getserviceId() == castOther.getserviceId())
				&& (this.getAppointmentId() == castOther.getAppointmentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getserviceId();
		result = 37 * result + this.getAppointmentId();
		return result;
	}

}
