package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Appointmentservice generated by hbm2java
 */
@Entity
@Table(name = "appointment_service", catalog = "pet_clinic1")
public class AppointmentService implements java.io.Serializable {

	private AppointmentServiceId id;
	private Appointment appointment;
	private service service;

	public AppointmentService() {
	}

	public AppointmentService(AppointmentServiceId id, Appointment appointment, service service) {
		this.id = id;
		this.appointment = appointment;
		this.service = service;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "serviceId", column = @Column(name = "service_id", nullable = false)),
			@AttributeOverride(name = "appointmentId", column = @Column(name = "appointment_id", nullable = false)) })
	public AppointmentServiceId getId() {
		return this.id;
	}

	public void setId(AppointmentServiceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "appointment_id", nullable = false, insertable = false, updatable = false)
	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_id", nullable = false, insertable = false, updatable = false)
	public service getservice() {
		return this.service;
	}

	public void setservice(service service) {
		this.service = service;
	}

}
