package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DoctorSchedule generated by hbm2java
 */
@Entity
@Table(name = "doctor_schedule", catalog = "pet_clinic1")
public class DoctorSchedule implements java.io.Serializable {

	private Integer scheduleId;
	private Doctor doctor;
	private String dayName;
	private Date startTime;
	private Date endTime;
	private Set<Scheduleservice> scheduleservices = new HashSet<Scheduleservice>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);

	public DoctorSchedule() {
	}

	public DoctorSchedule(Doctor doctor) {
		this.doctor = doctor;
	}

	public DoctorSchedule(Doctor doctor, String dayName, Date startTime, Date endTime,
			Set<Scheduleservice> scheduleservices, Set<Appointment> appointments) {
		this.doctor = doctor;
		this.dayName = dayName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.scheduleservices = scheduleservices;
		this.appointments = appointments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_id", unique = true, nullable = false)
	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@Column(name = "day_name", length = 4)
	public String getDayName() {
		return this.dayName;
	}

	public void setDayName(String dayName) {
		this.dayName = dayName;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "doctorSchedule")
	public Set<Scheduleservice> getScheduleservices() {
		return this.scheduleservices;
	}

	public void setScheduleservices(Set<Scheduleservice> scheduleservices) {
		this.scheduleservices = scheduleservices;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "doctorSchedule")
	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

}
