package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DoctorserviceId generated by hbm2java
 */
@Embeddable
public class DoctorserviceId implements java.io.Serializable {

	private int serviceTypeId;
	private int doctorId;

	public DoctorserviceId() {
	}

	public DoctorserviceId(int serviceTypeId, int doctorId) {
		this.serviceTypeId = serviceTypeId;
		this.doctorId = doctorId;
	}

	@Column(name = "service_type_id", nullable = false)
	public int getserviceTypeId() {
		return this.serviceTypeId;
	}

	public void setserviceTypeId(int serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "doctor_id", nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoctorserviceId))
			return false;
		DoctorserviceId castOther = (DoctorserviceId) other;

		return (this.getserviceTypeId() == castOther.getserviceTypeId())
				&& (this.getDoctorId() == castOther.getDoctorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getserviceTypeId();
		result = 37 * result + this.getDoctorId();
		return result;
	}

}
