package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Doctorservice generated by hbm2java
 */
@Entity
@Table(name = "doctor_service", catalog = "pet_clinic1")
public class DoctorService implements java.io.Serializable {

	private DoctorserviceId id;
	private Doctor doctor;
	private serviceType serviceType;

	public DoctorService() {
	}

	public DoctorService(DoctorserviceId id, Doctor doctor, serviceType serviceType) {
		this.id = id;
		this.doctor = doctor;
		this.serviceType = serviceType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "serviceTypeId", column = @Column(name = "service_type_id", nullable = false)),
			@AttributeOverride(name = "doctorId", column = @Column(name = "doctor_id", nullable = false)) })
	public DoctorserviceId getId() {
		return this.id;
	}

	public void setId(DoctorserviceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false, insertable = false, updatable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_type_id", nullable = false, insertable = false, updatable = false)
	public serviceType getserviceType() {
		return this.serviceType;
	}

	public void setserviceType(serviceType serviceType) {
		this.serviceType = serviceType;
	}

}
