package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Drug generated by hbm2java
 */
@Entity
@Table(name = "drug", catalog = "pet_clinic1")
public class Drug implements java.io.Serializable {

	private Integer drugId;
	private DrugType drugType;
	private String drugName;
	private String drugDesc;
	private String drugDurationType;
	private int drugDurationNo;
	private Set<PetDrugJoin> petDrugJoins = new HashSet<PetDrugJoin>(0);

	public Drug() {
	}

	public Drug(DrugType drugType, String drugName, String drugDesc, String drugDurationType, int drugDurationNo) {
		this.drugType = drugType;
		this.drugName = drugName;
		this.drugDesc = drugDesc;
		this.drugDurationType = drugDurationType;
		this.drugDurationNo = drugDurationNo;
	}

	public Drug(DrugType drugType, String drugName, String drugDesc, String drugDurationType, int drugDurationNo,
			Set<PetDrugJoin> petDrugJoins) {
		this.drugType = drugType;
		this.drugName = drugName;
		this.drugDesc = drugDesc;
		this.drugDurationType = drugDurationType;
		this.drugDurationNo = drugDurationNo;
		this.petDrugJoins = petDrugJoins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "drug_id", unique = true, nullable = false)
	public Integer getDrugId() {
		return this.drugId;
	}

	public void setDrugId(Integer drugId) {
		this.drugId = drugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_type_id", nullable = false)
	public DrugType getDrugType() {
		return this.drugType;
	}

	public void setDrugType(DrugType drugType) {
		this.drugType = drugType;
	}

	@Column(name = "drug_name", nullable = false, length = 50)
	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	@Column(name = "drug_desc", nullable = false, length = 200)
	public String getDrugDesc() {
		return this.drugDesc;
	}

	public void setDrugDesc(String drugDesc) {
		this.drugDesc = drugDesc;
	}

	@Column(name = "drug_duration_type", nullable = false, length = 5)
	public String getDrugDurationType() {
		return this.drugDurationType;
	}

	public void setDrugDurationType(String drugDurationType) {
		this.drugDurationType = drugDurationType;
	}

	@Column(name = "drug_duration_no", nullable = false)
	public int getDrugDurationNo() {
		return this.drugDurationNo;
	}

	public void setDrugDurationNo(int drugDurationNo) {
		this.drugDurationNo = drugDurationNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drug")
	public Set<PetDrugJoin> getPetDrugJoins() {
		return this.petDrugJoins;
	}

	public void setPetDrugJoins(Set<PetDrugJoin> petDrugJoins) {
		this.petDrugJoins = petDrugJoins;
	}

}
