package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DrugType generated by hbm2java
 */
@Entity
@Table(name = "drug_type", catalog = "pet_clinic1")
public class DrugType implements java.io.Serializable {

	private Integer drugTypeId;
	private String drugTypeName;
	private String drugTypeDesc;
	private Set<Drug> drugs = new HashSet<Drug>(0);

	public DrugType() {
	}

	public DrugType(String drugTypeName, String drugTypeDesc) {
		this.drugTypeName = drugTypeName;
		this.drugTypeDesc = drugTypeDesc;
	}

	public DrugType(String drugTypeName, String drugTypeDesc, Set<Drug> drugs) {
		this.drugTypeName = drugTypeName;
		this.drugTypeDesc = drugTypeDesc;
		this.drugs = drugs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "drug_type_id", unique = true, nullable = false)
	public Integer getDrugTypeId() {
		return this.drugTypeId;
	}

	public void setDrugTypeId(Integer drugTypeId) {
		this.drugTypeId = drugTypeId;
	}

	@Column(name = "drug_type_name", nullable = false, length = 50)
	public String getDrugTypeName() {
		return this.drugTypeName;
	}

	public void setDrugTypeName(String drugTypeName) {
		this.drugTypeName = drugTypeName;
	}

	@Column(name = "drug_type_desc", nullable = false, length = 200)
	public String getDrugTypeDesc() {
		return this.drugTypeDesc;
	}

	public void setDrugTypeDesc(String drugTypeDesc) {
		this.drugTypeDesc = drugTypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drugType")
	public Set<Drug> getDrugs() {
		return this.drugs;
	}

	public void setDrugs(Set<Drug> drugs) {
		this.drugs = drugs;
	}

}
