package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owner generated by hbm2java
 */
@Entity
@Table(name = "owner", catalog = "pet_clinic1")
public class Owner implements java.io.Serializable {

	private Integer ownerId;
	private String ownerName;
	private String ownerPh;
	private String ownerEmail;
	private String ownerAdd;
	private String ownerGender;
	private String ownerAddress;
	private Set<Appointment> appointments = new HashSet<Appointment>(0);
	private Set<Pet> pets = new HashSet<Pet>(0);

	public Owner() {
	}

	public Owner(String ownerName, String ownerPh, String ownerEmail, String ownerAdd, String ownerGender,
			String ownerAddress) {
		this.ownerName = ownerName;
		this.ownerPh = ownerPh;
		this.ownerEmail = ownerEmail;
		this.ownerAdd = ownerAdd;
		this.ownerGender = ownerGender;
		this.ownerAddress = ownerAddress;
	}

	public Owner(String ownerName, String ownerPh, String ownerEmail, String ownerAdd, String ownerGender,
			String ownerAddress, Set<Appointment> appointments, Set<Pet> pets) {
		this.ownerName = ownerName;
		this.ownerPh = ownerPh;
		this.ownerEmail = ownerEmail;
		this.ownerAdd = ownerAdd;
		this.ownerGender = ownerGender;
		this.ownerAddress = ownerAddress;
		this.appointments = appointments;
		this.pets = pets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "owner_id", unique = true, nullable = false)
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "owner_name", nullable = false, length = 20)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "owner_ph", nullable = false, length = 20)
	public String getOwnerPh() {
		return this.ownerPh;
	}

	public void setOwnerPh(String ownerPh) {
		this.ownerPh = ownerPh;
	}

	@Column(name = "owner_email", nullable = false, length = 50)
	public String getOwnerEmail() {
		return this.ownerEmail;
	}

	public void setOwnerEmail(String ownerEmail) {
		this.ownerEmail = ownerEmail;
	}

	@Column(name = "owner_add", nullable = false, length = 100)
	public String getOwnerAdd() {
		return this.ownerAdd;
	}

	public void setOwnerAdd(String ownerAdd) {
		this.ownerAdd = ownerAdd;
	}

	@Column(name = "owner_gender", nullable = false, length = 2)
	public String getOwnerGender() {
		return this.ownerGender;
	}

	public void setOwnerGender(String ownerGender) {
		this.ownerGender = ownerGender;
	}

	@Column(name = "owner_address", nullable = false, length = 200)
	public String getOwnerAddress() {
		return this.ownerAddress;
	}

	public void setOwnerAddress(String ownerAddress) {
		this.ownerAddress = ownerAddress;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "owner")
	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "owner")
	public Set<Pet> getPets() {
		return this.pets;
	}

	public void setPets(Set<Pet> pets) {
		this.pets = pets;
	}

}
