package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name = "payment_type", catalog = "pet_clinic1")
public class PaymentType implements java.io.Serializable {

	private Integer paymentTypeId;
	private String paymentTypeName;
	private Set<Vocher> vochers = new HashSet<Vocher>(0);

	public PaymentType() {
	}

	public PaymentType(String paymentTypeName) {
		this.paymentTypeName = paymentTypeName;
	}

	public PaymentType(String paymentTypeName, Set<Vocher> vochers) {
		this.paymentTypeName = paymentTypeName;
		this.vochers = vochers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_type_id", unique = true, nullable = false)
	public Integer getPaymentTypeId() {
		return this.paymentTypeId;
	}

	public void setPaymentTypeId(Integer paymentTypeId) {
		this.paymentTypeId = paymentTypeId;
	}

	@Column(name = "payment_type_name", nullable = false, length = 40)
	public String getPaymentTypeName() {
		return this.paymentTypeName;
	}

	public void setPaymentTypeName(String paymentTypeName) {
		this.paymentTypeName = paymentTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentType")
	public Set<Vocher> getVochers() {
		return this.vochers;
	}

	public void setVochers(Set<Vocher> vochers) {
		this.vochers = vochers;
	}

}
