package com.coder.model;
// Generated Aug 4, 2020 2:43:24 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table(name = "pet", catalog = "pet_clinic1")
public class Pet implements java.io.Serializable {

	private Integer petId;
	private Owner owner;
	private Species species;
	private String petName;
	private String petSex;
	private Date petBirth;
	private Date petDeath;
	private Set<PetDrug> petDrugs = new HashSet<PetDrug>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);

	public Pet() {
	}

	public Pet(Owner owner, Species species) {
		this.owner = owner;
		this.species = species;
	}

	public Pet(Owner owner, Species species, String petName, String petSex, Date petBirth, Date petDeath,
			Set<PetDrug> petDrugs, Set<Appointment> appointments) {
		this.owner = owner;
		this.species = species;
		this.petName = petName;
		this.petSex = petSex;
		this.petBirth = petBirth;
		this.petDeath = petDeath;
		this.petDrugs = petDrugs;
		this.appointments = appointments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pet_id", unique = true, nullable = false)
	public Integer getPetId() {
		return this.petId;
	}

	public void setPetId(Integer petId) {
		this.petId = petId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = false)
	public Owner getOwner() {
		return this.owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "species_id", nullable = false)
	public Species getSpecies() {
		return this.species;
	}

	public void setSpecies(Species species) {
		this.species = species;
	}

	@Column(name = "pet_name", length = 30)
	public String getPetName() {
		return this.petName;
	}

	public void setPetName(String petName) {
		this.petName = petName;
	}

	@Column(name = "pet_sex", length = 2)
	public String getPetSex() {
		return this.petSex;
	}

	public void setPetSex(String petSex) {
		this.petSex = petSex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pet_birth", length = 10)
	public Date getPetBirth() {
		return this.petBirth;
	}

	public void setPetBirth(Date petBirth) {
		this.petBirth = petBirth;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pet_death", length = 10)
	public Date getPetDeath() {
		return this.petDeath;
	}

	public void setPetDeath(Date petDeath) {
		this.petDeath = petDeath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<PetDrug> getPetDrugs() {
		return this.petDrugs;
	}

	public void setPetDrugs(Set<PetDrug> petDrugs) {
		this.petDrugs = petDrugs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

}
