package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PetDrug generated by hbm2java
 */
@Entity
@Table(name = "pet_drug", catalog = "pet_clinic1")
public class PetDrug implements java.io.Serializable {

	private Integer petDrugId;
	private Appointment appointment;
	private Doctor doctor;
	private Pet pet;
	private Date drugDate;
	private Date drugNextDate;
	private String drugDesc;
	private Set<PetDrugJoin> petDrugJoins = new HashSet<PetDrugJoin>(0);
	private Set<Vocher> vochers = new HashSet<Vocher>(0);

	public PetDrug() {
	}

	public PetDrug(Appointment appointment, Doctor doctor, Pet pet) {
		this.appointment = appointment;
		this.doctor = doctor;
		this.pet = pet;
	}

	public PetDrug(Appointment appointment, Doctor doctor, Pet pet, Date drugDate, Date drugNextDate, String drugDesc,
			Set<PetDrugJoin> petDrugJoins, Set<Vocher> vochers) {
		this.appointment = appointment;
		this.doctor = doctor;
		this.pet = pet;
		this.drugDate = drugDate;
		this.drugNextDate = drugNextDate;
		this.drugDesc = drugDesc;
		this.petDrugJoins = petDrugJoins;
		this.vochers = vochers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pet_drug_id", unique = true, nullable = false)
	public Integer getPetDrugId() {
		return this.petDrugId;
	}

	public void setPetDrugId(Integer petDrugId) {
		this.petDrugId = petDrugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appointment_id", nullable = false)
	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_id", nullable = false)
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "drug_date", length = 10)
	public Date getDrugDate() {
		return this.drugDate;
	}

	public void setDrugDate(Date drugDate) {
		this.drugDate = drugDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "drug_next_date", length = 10)
	public Date getDrugNextDate() {
		return this.drugNextDate;
	}

	public void setDrugNextDate(Date drugNextDate) {
		this.drugNextDate = drugNextDate;
	}

	@Column(name = "drug_desc", length = 50)
	public String getDrugDesc() {
		return this.drugDesc;
	}

	public void setDrugDesc(String drugDesc) {
		this.drugDesc = drugDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petDrug")
	public Set<PetDrugJoin> getPetDrugJoins() {
		return this.petDrugJoins;
	}

	public void setPetDrugJoins(Set<PetDrugJoin> petDrugJoins) {
		this.petDrugJoins = petDrugJoins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petDrug")
	public Set<Vocher> getVochers() {
		return this.vochers;
	}

	public void setVochers(Set<Vocher> vochers) {
		this.vochers = vochers;
	}

}
