package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PetDrugJoinId generated by hbm2java
 */
@Embeddable
public class PetDrugJoinId implements java.io.Serializable {

	private int drugId;
	private int petDrugId;

	public PetDrugJoinId() {
	}

	public PetDrugJoinId(int drugId, int petDrugId) {
		this.drugId = drugId;
		this.petDrugId = petDrugId;
	}

	@Column(name = "drug_id", nullable = false)
	public int getDrugId() {
		return this.drugId;
	}

	public void setDrugId(int drugId) {
		this.drugId = drugId;
	}

	@Column(name = "pet_drug_id", nullable = false)
	public int getPetDrugId() {
		return this.petDrugId;
	}

	public void setPetDrugId(int petDrugId) {
		this.petDrugId = petDrugId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PetDrugJoinId))
			return false;
		PetDrugJoinId castOther = (PetDrugJoinId) other;

		return (this.getDrugId() == castOther.getDrugId()) && (this.getPetDrugId() == castOther.getPetDrugId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDrugId();
		result = 37 * result + this.getPetDrugId();
		return result;
	}

}
