package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PetDrugJoin generated by hbm2java
 */
@Entity
@Table(name = "pet_drug_join", catalog = "pet_clinic1")
public class PetDrugJoin implements java.io.Serializable {

	private PetDrugJoinId id;
	private Drug drug;
	private PetDrug petDrug;

	public PetDrugJoin() {
	}

	public PetDrugJoin(PetDrugJoinId id, Drug drug, PetDrug petDrug) {
		this.id = id;
		this.drug = drug;
		this.petDrug = petDrug;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "drugId", column = @Column(name = "drug_id", nullable = false)),
			@AttributeOverride(name = "petDrugId", column = @Column(name = "pet_drug_id", nullable = false)) })
	public PetDrugJoinId getId() {
		return this.id;
	}

	public void setId(PetDrugJoinId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_id", nullable = false, insertable = false, updatable = false)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_drug_id", nullable = false, insertable = false, updatable = false)
	public PetDrug getPetDrug() {
		return this.petDrug;
	}

	public void setPetDrug(PetDrug petDrug) {
		this.petDrug = petDrug;
	}

}
