package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PetLogin generated by hbm2java
 */
@Entity
@Table(name = "pet_login", catalog = "pet_clinic1")
public class PetLogin implements java.io.Serializable {

	private String loginId;
	private String password;
	private String userName;

	public PetLogin() {
	}

	public PetLogin(String loginId, String password, String userName) {
		this.loginId = loginId;
		this.password = password;
		this.userName = userName;
	}

	@Id

	@Column(name = "login_id", unique = true, nullable = false, length = 20)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "password", nullable = false, length = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_name", nullable = false, length = 40)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
