package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rank generated by hbm2java
 */
@Entity
@Table(name = "rank", catalog = "pet_clinic1")
public class Rank implements java.io.Serializable {

	private Integer rankId;
	private String rankName;
	private String shortTerm;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);

	public Rank() {
	}

	public Rank(String rankName, String shortTerm) {
		this.rankName = rankName;
		this.shortTerm = shortTerm;
	}

	public Rank(String rankName, String shortTerm, Set<Doctor> doctors) {
		this.rankName = rankName;
		this.shortTerm = shortTerm;
		this.doctors = doctors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rank_id", unique = true, nullable = false)
	public Integer getRankId() {
		return this.rankId;
	}

	public void setRankId(Integer rankId) {
		this.rankId = rankId;
	}

	@Column(name = "rank_name", nullable = false, length = 40)
	public String getRankName() {
		return this.rankName;
	}

	public void setRankName(String rankName) {
		this.rankName = rankName;
	}

	@Column(name = "short_term", nullable = false, length = 20)
	public String getShortTerm() {
		return this.shortTerm;
	}

	public void setShortTerm(String shortTerm) {
		this.shortTerm = shortTerm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rank")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

}
