package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Scheduleservice generated by hbm2java
 */
@Entity
@Table(name = "schedule_service", catalog = "pet_clinic1")
public class Scheduleservice implements java.io.Serializable {

	private ScheduleserviceId id;
	private DoctorSchedule doctorSchedule;
	private serviceType serviceType;

	public Scheduleservice() {
	}

	public Scheduleservice(ScheduleserviceId id, DoctorSchedule doctorSchedule, serviceType serviceType) {
		this.id = id;
		this.doctorSchedule = doctorSchedule;
		this.serviceType = serviceType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "serviceTypeId", column = @Column(name = "service_type_id", nullable = false)),
			@AttributeOverride(name = "scheduleId", column = @Column(name = "schedule_id", nullable = false)) })
	public ScheduleserviceId getId() {
		return this.id;
	}

	public void setId(ScheduleserviceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "schedule_id", nullable = false, insertable = false, updatable = false)
	public DoctorSchedule getDoctorSchedule() {
		return this.doctorSchedule;
	}

	public void setDoctorSchedule(DoctorSchedule doctorSchedule) {
		this.doctorSchedule = doctorSchedule;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_type_id", nullable = false, insertable = false, updatable = false)
	public serviceType getserviceType() {
		return this.serviceType;
	}

	public void setserviceType(serviceType serviceType) {
		this.serviceType = serviceType;
	}

}
