package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScheduleserviceId generated by hbm2java
 */
@Embeddable
public class ScheduleserviceId implements java.io.Serializable {

	private int serviceTypeId;
	private int scheduleId;

	public ScheduleserviceId() {
	}

	public ScheduleserviceId(int serviceTypeId, int scheduleId) {
		this.serviceTypeId = serviceTypeId;
		this.scheduleId = scheduleId;
	}

	@Column(name = "service_type_id", nullable = false)
	public int getserviceTypeId() {
		return this.serviceTypeId;
	}

	public void setserviceTypeId(int serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "schedule_id", nullable = false)
	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScheduleserviceId))
			return false;
		ScheduleserviceId castOther = (ScheduleserviceId) other;

		return (this.getserviceTypeId() == castOther.getserviceTypeId())
				&& (this.getScheduleId() == castOther.getScheduleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getserviceTypeId();
		result = 37 * result + this.getScheduleId();
		return result;
	}

}
