package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "pet_clinic1")
public class service implements java.io.Serializable {

	private Integer serviceId;
	private serviceType serviceType;
	private String serviceName;
	private int servicePoint;
	private int serviceMinute;
	private String serviceAbout;
	private Set<Appointmentservice> appointmentservices = new HashSet<Appointmentservice>(0);

	public service() {
	}

	public service(serviceType serviceType, String serviceName, int servicePoint, int serviceMinute, String serviceAbout) {
		this.serviceType = serviceType;
		this.serviceName = serviceName;
		this.servicePoint = servicePoint;
		this.serviceMinute = serviceMinute;
		this.serviceAbout = serviceAbout;
	}

	public service(serviceType serviceType, String serviceName, int servicePoint, int serviceMinute, String serviceAbout,
			Set<Appointmentservice> appointmentservices) {
		this.serviceType = serviceType;
		this.serviceName = serviceName;
		this.servicePoint = servicePoint;
		this.serviceMinute = serviceMinute;
		this.serviceAbout = serviceAbout;
		this.appointmentservices = appointmentservices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_id", unique = true, nullable = false)
	public Integer getserviceId() {
		return this.serviceId;
	}

	public void setserviceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_type_id", nullable = false)
	public serviceType getserviceType() {
		return this.serviceType;
	}

	public void setserviceType(serviceType serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "service_name", nullable = false, length = 60)
	public String getserviceName() {
		return this.serviceName;
	}

	public void setserviceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "service_point", nullable = false)
	public int getservicePoint() {
		return this.servicePoint;
	}

	public void setservicePoint(int servicePoint) {
		this.servicePoint = servicePoint;
	}

	@Column(name = "service_minute", nullable = false)
	public int getserviceMinute() {
		return this.serviceMinute;
	}

	public void setserviceMinute(int serviceMinute) {
		this.serviceMinute = serviceMinute;
	}

	@Column(name = "service_about", nullable = false, length = 200)
	public String getserviceAbout() {
		return this.serviceAbout;
	}

	public void setserviceAbout(String serviceAbout) {
		this.serviceAbout = serviceAbout;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "service")
	public Set<Appointmentservice> getAppointmentservices() {
		return this.appointmentservices;
	}

	public void setAppointmentservices(Set<Appointmentservice> appointmentservices) {
		this.appointmentservices = appointmentservices;
	}

}
