package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * serviceType generated by hbm2java
 */
@Entity
@Table(name = "service_type", catalog = "pet_clinic1")
public class serviceType implements java.io.Serializable {

	private Integer serviceTypeId;
	private String serviceTypeName;
	private int averageTime;
	private String serviceTypeDesc;
	private Set<service> services = new HashSet<service>(0);
	private Set<Doctorservice> doctorservices = new HashSet<Doctorservice>(0);
	private Set<Scheduleservice> scheduleservices = new HashSet<Scheduleservice>(0);

	public serviceType() {
	}

	public serviceType(String serviceTypeName, String serviceTypeDesc,int averageTime) {
		this.serviceTypeName = serviceTypeName;
		this.serviceTypeDesc = serviceTypeDesc;
		this.averageTime=averageTime;
	}

	public serviceType(String serviceTypeName, String serviceTypeDesc,int averageTime, Set<service> services,
		Set<Doctorservice> doctorservices, Set<Scheduleservice> scheduleservices) {
		this.serviceTypeName = serviceTypeName;
		this.serviceTypeDesc = serviceTypeDesc;
		this.averageTime=averageTime;
		this.services = services;
		this.doctorservices = doctorservices;
		this.scheduleservices = scheduleservices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_type_id", unique = true, nullable = false)
	public Integer getserviceTypeId() {
		return this.serviceTypeId;
	}

	public void setserviceTypeId(Integer serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "service_type_name", nullable = false, length = 30)
	public String getserviceTypeName() {
		return this.serviceTypeName;
	}

	public void setserviceTypeName(String serviceTypeName) {
		this.serviceTypeName = serviceTypeName;
	}

	@Column(name = "service_type_desc", nullable = false, length = 100)
	public String getserviceTypeDesc() {
		return this.serviceTypeDesc;
	}

	public void setserviceTypeDesc(String serviceTypeDesc) {
		this.serviceTypeDesc = serviceTypeDesc;
	}
	@Column(name = "average_time", nullable = false)
	public int getAverageTime() {
		return this.averageTime;
	}

	public void setAverageTime(int averageTime) {
		this.averageTime = averageTime;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "serviceType")
	public Set<service> getservices() {
		return this.services;
	}

	public void setservices(Set<service> services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "serviceType")
	public Set<Doctorservice> getDoctorservices() {
		return this.doctorservices;
	}

	public void setDoctorservices(Set<Doctorservice> doctorservices) {
		this.doctorservices = doctorservices;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "serviceType")
	public Set<Scheduleservice> getScheduleservices() {
		return this.scheduleservices;
	}

	public void setScheduleservices(Set<Scheduleservice> scheduleservices) {
		this.scheduleservices = scheduleservices;
	}

}
