package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vocher generated by hbm2java
 */
@Entity
@Table(name = "vocher", catalog = "pet_clinic1")
public class Vocher implements java.io.Serializable {

	private Integer voucherNo;
	private PaymentType paymentType;
	private PetDrug petDrug;
	private Date voucherDate;
	private int totalAmount;
	private String vocherDesc;

	public Vocher() {
	}

	public Vocher(PaymentType paymentType, PetDrug petDrug, Date voucherDate, int totalAmount, String vocherDesc) {
		this.paymentType = paymentType;
		this.petDrug = petDrug;
		this.voucherDate = voucherDate;
		this.totalAmount = totalAmount;
		this.vocherDesc = vocherDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "voucher_no", unique = true, nullable = false)
	public Integer getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(Integer voucherNo) {
		this.voucherNo = voucherNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_type_id", nullable = false)
	public PaymentType getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_drug_id", nullable = false)
	public PetDrug getPetDrug() {
		return this.petDrug;
	}

	public void setPetDrug(PetDrug petDrug) {
		this.petDrug = petDrug;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "voucher_date", nullable = false, length = 10)
	public Date getVoucherDate() {
		return this.voucherDate;
	}

	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}

	@Column(name = "total_amount", nullable = false)
	public int getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(int totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "vocher_desc", nullable = false, length = 200)
	public String getVocherDesc() {
		return this.vocherDesc;
	}

	public void setVocherDesc(String vocherDesc) {
		this.vocherDesc = vocherDesc;
	}

}
